spring.application.name=backend
# Archivo de base de datos H2 persistente
spring.datasource.url=jdbc:h2:file:./data/tareasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Creación/Actualización automática de tablas en Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2
spring.h2.console.enabled=true
